# Generated by Django 5.1.3 on 2024-11-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
