# Generated by Django 5.1.3 on 2024-12-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0006_profileparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileparent',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
