# Generated by Django 5.1.3 on 2024-12-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('Parenting Dasar', 'Parenting Dasar'), ('Ide Bekal Sekolah', 'Ide Bekal Sekolah'), ('Ruang Baca', 'Ruang Baca'), ('Animal', 'Animal'), ('ABC & 123', 'ABC & 123'), ('Warna & Bentuk', 'Warna & Bentuk'), ('Science', 'Science')], max_length=255, null=True)),
            ],
        ),
    ]
